### ISSUE TITLE
Feature Request: Please add ability to create shares from Terraform

### ISSUE THREAD

**Issue by volovva** [Keeper-Security/terraform-provider-secretsmanager#25]
Please add ability to share a record (created by Terraform) with specific user or Team in Keeper via Terraform.
That would allow full lifecycle of a record in Terraform, from creation to sharing instead of using Terraform + CLI

This is related to https://github.com/Keeper-Security/terraform-provider-secretsmanager/issues/10 which speaks about entire folders

**Comment by idimov-keeper** [comment]
Terraform plugin is based on Secrets Manager ([Go SDK](https://github.com/Keeper-Security/secrets-manager-go)) and KSM is limited only to data access by design (pulling secrets from KSM App) - cannot handle sharing, users/teams etc. KSM can only create a sub-folder(s) in a shared folder and so called "Folder Management" is limited to only listing/navigating shared folders (only those shared to the KSM App) and full CRUD for sub-folders.
